version: "3.8"

networks:
  ticketService-net:
    driver: bridge

services:
  ticketService-backend:
    container_name: ticketService-backend
    hostname: ticketService
    image: ticketservice:latest
    build: .
    environment:
      H2_DATABASE_LOCATION: ${H2_DATABASE_LOCATION}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      NEO4J_DATABASE: ${NEO4J_DATABASE}
      NEO4J_USERNAME: ${NEO4J_USERNAME}
      NEO4J_PASSWORD: ${NEO4J_PASSWORD}
      NEO4J_URI: ${NEO4J_URI}
      FRONTEND_URL: ${FRONTEND_URL}
    ports:
      - "8080:8080"
    networks:
      - ticketService-net
    depends_on:
      - neo4j
    env_file:
      - .env

  ticketService-frontend:
    container_name: ticketService-frontend
    image: ticketservice-frontend:latest
    build:
      context: frontend
      dockerfile: Dockerfile
    ports:
      - "3001:80"
      - "3002:3001"
    networks:
      - ticketService-net

  neo4j:
    container_name: neo4j
    image: neo4j:5.26.4-community
    build:
      context: neo4j
      dockerfile: Dockerfile
    hostname: neo4j
    environment:
      NEO4J_AUTH: ${NEO4J_AUTH}
      NEO4J_PLUGINS: ${NEO4J_PLUGINS}
      NEO4J_apoc_export_file_enabled: ${NEO4J_apoc_export_file_enabled}
      NEO4J_apoc_import_file_enabled: ${NEO4J_apoc_import_file_enabled}
      NEO4J_apoc_import_file_use__neo4j__config: ${NEO4J_apoc_import_file_use__neo4j__config}
      NEO4J_server_directories_import: "/"
      NEO4J_apoc_initializer_neo4j_cypher: 'CALL apoc.cypher.runFile("file:///scripts/init.cypher");'
    ports:
      - "7474:7474"
      - "7687:7687"
    networks:
      - ticketService-net
    volumes:
      - "./neo4j-data:/data"
      - "./neo4j-logs:/logs"
      - "./neo4j-plugins:/var/lib/neo4j/plugins"
    env_file:
      - .env